### ISSUE TITLE
Android app does not detect the ESL blaster

### ISSUE THREAD

**Issue by kilo3421** [furrtek/PrecIR#19]
With the latest app version, the blaster still reads "Disconnected" and the TX is greyed out.

On the screenshot, you can see the red light in the middle of the 5.

(Included usb-A to usb-C cable)
![image](https://github.com/furrtek/PrecIR/assets/45699403/ec79dd6d-819f-4e51-bed3-7e797854cbfa)

**Comment by furrtek** [comment]
Hello.
Do you have OTG enabled on your phone ?
It's sometimes disabled by default, or after 15 minutes without USB activity.

**Comment by kilo3421** [comment]
OTG is enabled by default, i did test with an USB device.
I don't think ive reached the 15 min afk.
Also, to mention, i have an S20 FE 5G

Thanks.

**Comment by kilo3421** [comment]
After receiving an good cable, the cable provided with the Tindie order is faulty. The phone does connect to the ESL blaster.
