### ISSUE TITLE
ESL Blaster Not working on Epaper type

### ISSUE THREAD

**Issue by msoffice95** [furrtek/PrecIR#4]
Does not work on Epaper type when it is set to the "Unlinked mode"
This mode is how it is received new 
Command used: img2dm.py com7 checker.png <ESL ID> 0

**Comment by msoffice95** [comment]
Timeout on COM7
It says to use Python 2 but imageio requires 3.6> and above

**Comment by furrtek** [comment]
Please use Python 3.
