### ISSUE TITLE
Barcode format?

### ISSUE THREAD

**Issue by evm-sec** [furrtek/PrecIR#5]
Can you explain (maybe with an image) how to pull the "17-digit barcode string" from a label device?  I recently got an HD150 model, the barcode on the screen is in the format 5-2 2-4-4-2-4 (# of digits).  The barcode on the back has a 17 digit barcode starting with "A" - although I assume it's probably the barcode on the front.  I got an ESL Blaster and tried it with the 17-digit barcode string on the back, but no luck.  Full disclosure: I'm on Linux and had to modify tx.py to search for /dev/ttyACM* instead of COM*, but it appeared to work after that.

**Comment by furrtek** [comment]
The barcode from which the label ID is extracted is indeed the one on the back: http://furrtek.free.fr/noclass/esl/eslbarcode.png
Does the ESL Blaster's red LED turn on ?

**Comment by evm-apl** [comment]
Yeah, the red LED came on on the ESL Blaster, although I saw no response from the HD150 tag.  I tried to hold it close to the Blaster and tried it from different angles.  Didn't see anything response or change on the HD150.  I didn't modify the ESL Blaster in any way, it's running whatever firmware you shipped it with. :-)

Here's the output - I double and triple checked that the barcode string matches the string immediately below the barcode on the back.

~/Pricer/PrecIR/tools_python$ sudo python2 img2dm.py 0 foo.png A4108261934813544 0 
Found ESL Blaster on /dev/ttyACM0
Compressing 19902 pixels...
Compression ratio: 52.1%
Generating 60 data frames...
Transmitting frame 1/63, length 34, repeated 400 times.
Transmitting frame 2/63, length 34, repeated 1 times.
Transmitting frame 3/63, length 34, repeated 1 times.
Transmitting frame 4/63, length 34, repeated 1 times.
Transmitting frame 5/63, length 34, repeated 1 times.
Transmitting frame 6/63, length 34, repeated 1 times.
Transmitting frame 7/63, length 34, repeated 1 times.
Transmitting frame 8/63, length 34, repeated 1 times.
Transmitting frame 9/63, length 34, repeated 1 times.
Transmitting frame 10/63, length 34, repeated 1 times.
Transmitting frame 11/63, length 34, repeated 1 times.
Transmitting frame 12/63, length 34, repeated 1 times.
Transmitting frame 13/63, length 34, repeated 1 times.
Transmitting frame 14/63, length 34, repeated 1 times.
Transmitting frame 15/63, length 34, repeated 1 times.
Transmitting frame 16/63, length 34, repeated 1 times.
Transmitting frame 17/63, length 34, repeated 1 times.
Transmitting frame 18/63, length 34, repeated 1 times.
Transmitting frame 19/63, length 34, repeated 1 times.
Transmitting frame 20/63, length 34, repeated 1 times.
Transmitting frame 21/63, length 34, repeated 1 times.
Transmitting frame 22/63, length 34, repeated 1 times.
Transmitting frame 23/63, length 34, repeated 1 times.
Transmitting frame 24/63, length 34, repeated 1 times.
Transmitting frame 25/63, length 34, repeated 1 times.
Transmitting frame 26/63, length 34, repeated 1 times.
Transmitting frame 27/63, length 34, repeated 1 times.
Transmitting frame 28/63, length 34, repeated 1 times.
Transmitting frame 29/63, length 34, repeated 1 times.
Transmitting frame 30/63, length 34, repeated 1 times.
Transmitting frame 31/63, length 34, repeated 1 times.
Transmitting frame 32/63, length 34, repeated 1 times.
Transmitting frame 33/63, length 34, repeated 1 times.
Transmitting frame 34/63, length 34, repeated 1 times.
Transmitting frame 35/63, length 34, repeated 1 times.
Transmitting frame 36/63, length 34, repeated 1 times.
Transmitting frame 37/63, length 34, repeated 1 times.
Transmitting frame 38/63, length 34, repeated 1 times.
Transmitting frame 39/63, length 34, repeated 1 times.
Transmitting frame 40/63, length 34, repeated 1 times.
Transmitting frame 41/63, length 34, repeated 1 times.
Transmitting frame 42/63, length 34, repeated 1 times.
Transmitting frame 43/63, length 34, repeated 1 times.
Transmitting frame 44/63, length 34, repeated 1 times.
Transmitting frame 45/63, length 34, repeated 1 times.
Transmitting frame 46/63, length 34, repeated 1 times.
Transmitting frame 47/63, length 34, repeated 1 times.
Transmitting frame 48/63, length 34, repeated 1 times.
Transmitting frame 49/63, length 34, repeated 1 times.
Transmitting frame 50/63, length 34, repeated 1 times.
Transmitting frame 51/63, length 34, repeated 1 times.
Transmitting frame 52/63, length 34, repeated 1 times.
Transmitting frame 53/63, length 34, repeated 1 times.
Transmitting frame 54/63, length 34, repeated 1 times.
Transmitting frame 55/63, length 34, repeated 1 times.
Transmitting frame 56/63, length 34, repeated 1 times.
Transmitting frame 57/63, length 34, repeated 1 times.
Transmitting frame 58/63, length 34, repeated 1 times.
Transmitting frame 59/63, length 34, repeated 1 times.
Transmitting frame 60/63, length 34, repeated 1 times.
Transmitting frame 61/63, length 34, repeated 1 times.
Transmitting frame 62/63, length 34, repeated 1 times.
Transmitting frame 63/63, length 34, repeated 1 times.
Done. Please allow a few seconds for the ESL to refresh.
